### teste de login ###
POST http://localhost:4000/Login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "senha": "admin"
}


### teste de buscar todas as contas ###
GET http://localhost:4000/contas HTTP/1.1
content-type: application/json


### teste de buscar conta por ID ###
GET http://localhost:4000/contas/7100dd4b-a1c2-4d80-a9eb-3686f7def325 HTTP/1.1
content-type: application/json


### teste de inserção de conta ###

POST http://localhost:4000/contas HTTP/1.1
content-type: application/json

{
    "descricao": "Conta do felipe",
    "tipo": "Despesa",
    "valor": 150.00,
    "data": "2024-11-13",
    "status": "Pendente",
    "forma_pagamento": "Cartão de crédito",
    "usuario_id": "bcd2bf3e-a355-4d01-b320-8f35ca96f525"

}

### teste de atualização de conta ###
Put http://localhost:4000/contas/c1ae01a9-37a0-4062-a51a-0a1c5854ab27 HTTP/1.1
content-type: application/json


{
    "descricao": "Conta de luz atualizada kkkkkkkkkkkkk",
    "tipo": "Despesa",
    "valor": 160.00,
    "data": "2024-11-14",
    "status": "Paga",
    "forma_pagamento": "Débito",
    "usuario_id":"bcd2bf3e-a355-4d01-b320-8f35ca96f525"
}

### teste de exclusão de conta ###
delete http://localhost:4000/contas/c1ae01a9-37a0-4062-a51a-0a1c5854ab27 HTTP/1.1
content-type: application/json

